spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:mysql}:3306/sbpe
    username: root
    password: pass
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    root: INFO
    org.springframework: INFO
