# docker-compose -f docker-compose-sbpe.yml up -d

# export REDIS_PORT=6380
# export MYSQL_PORT=3307

version: '3.7'
services:
  api:
    container_name: api
    env_file:
      - ./.env
    networks:
      - sbpe
    ports:
      - "${API_PORT:-8080}:8080"
  cache:
    container_name: redis
    image: redis:4
    networks:
      - sbpe
    volumes:
      - ./volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT:-6379}:6379"
  rdb:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    networks:
      - sbpe
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
  kvs:
    container_name: bigtable
    image: bigtruedata/gcloud-bigtable-emulator
    networks:
      - sbpe
    ports:
      - "${BIGTABLE_PORT:-8086}:8086"
networks:
  default:
    name: sbpe
