version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:4
    ports:
      - "${REDIS_PORT:-6379}:6379"
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sbpe
    ports:
      - "${MYSQL_PORT:-3306}:3306"
  bigtable:
    container_name: bigtable
    image: bigtruedata/gcloud-bigtable-emulator
    ports:
      - "${BIGTABLE_PORT:-8086}:8086"
