spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sbpe
    username: root
    password: pass
    initialization-mode: always
  jpa:
    database: mysql
logging:
  level:
    root: INFO
    org.springframework: INFO
