CREATE DATABASE IF NOT EXISTS sbpe DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE sbpe;

CREATE TABLE IF NOT EXISTS developer(
  id BIGINT(20) NOT NULL,
  name VARCHAR(128) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
