name: CI test
on: [push]

env:
  MYSQL_PORT: 3307

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Check code format
        run: mvn com.coveo:fmt-maven-plugin:check

      - name: docker-compose up
        run: |
          cd docker
          docker-compose up -d

      - name: Run test code
        run: mvn test
